#pragma config(Sensor, dgtl7,  liftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl10, greenled,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, yellowled,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, redled,         sensorLEDtoVCC)
#pragma config(Motor,  port1,           bottomLift,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port2,           frontRight,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           frontLeft,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           linearLift,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           clawRotate,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           clawOpenClose, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          topLift,       tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DEBUG


#include "batterymonitor.c"
//#include "smoothmotor.c"
#include "logic.c"
#include "joystick.c"

task main()
{
  startTask(battery_monitor);
  startTask(control);
  startTask(joystick_controller_control);
  //is_joystick_control = false;
  while(true);
  //startTask(motor_movement);
}
